
-- Settings here
igen_pregenerate_defaults = true -- Does this mod automatically produce a series of item generators for default?
igen_log_item_movements = false -- Does this mod log any item transactions to or from a item generator? (Can produce more content in logs)
igen_log_item_generation = false -- Does this mod log any item generated by an item generator? (Can produce more content in logs)
igen_mcl2_support = false -- Enable this if this is a MineClone2 server! (I do not auto-detect this!)
igen_secure_generators = true -- If able, do we allow the generator to behave like a locked chest or do we simply act like a default chest? (true for locked)
                              -- Due to the way MineClone2 chests work, security is automatically disabled on those servers!
--[[ Default settings (Reference only, not used, DO NOT CHANGE!!!)
igen_pregenerate_defaults = true
igen_log_item_movements = false
igen_log_item_generation = false
igen_mcl2_support = false
igen_secure_generators = true
]]--
