
-- Settings here
igen_pregenerate_defaults = true -- Does this mod automatically produce a series of item generators for default?
igen_hopper_support = true       -- Does this mod if able include support for the hopper mod?
igen_log_hopper_supports = false -- Does this mod log if a item generator got support from hopper mod? (Can produce more content in logs)
igen_log_item_movements = false  -- Does this mod log any item transactions to or from a item generator? (Can produce more content in logs)
igen_log_item_generation = false -- Does this mod log any item generated by an item generator? (Can produce more content in logs)
igen_log_generator_creation = false -- Does this mod log any generator created by the api? (Only switch to off if in production)