
-- Settings here
igen_pregenerate_defaults = true -- Does this mod automatically produce a series of item generators for default?
igen_log_item_movements = false -- Does this mod log any item transactions to or from a item generator? (Can produce more content in logs)
igen_log_item_generation = false -- Does this mod log any item generated by an item generator? (Can produce more content in logs)
igen_allow_insecure_generators = true -- Do we allow insecure generators to be crafted?

--[[ Default settings (Reference only, not used, DO NOT CHANGE!!!)
igen_pregenerate_defaults = true
igen_log_item_movements = false
igen_log_item_generation = false
igen_allow_insecure_generators = true
]]--
